import Phaser from 'phaser';
import { GameSession,GAME_DATA } from '../core/GameSession';import type { EnemyDefinition,ModeDefinition,RoomDefinition,RoomState } from '../types/game';import { FixedStepSimulation } from '../systems/FixedStepSimulation';import { CombatSystem,type Damageable } from '../systems/CombatSystem';import { AudioSystem } from '../systems/AudioSystem';import { SaveSystem } from '../systems/SaveSystem';import { button } from '../ui/Button';import { FEATURES } from '../config/features';

type EnemyRuntime=Damageable&{type:string;def:EnemyDefinition;body:Phaser.GameObjects.Container;shape:Phaser.GameObjects.Arc;hpBar:Phaser.GameObjects.Rectangle;state:'SPAWNING'|'SEARCHING'|'MOVING'|'ATTACKING'|'HIT'|'DYING'|'DEAD';cooldown:number;targetRoomId:string|null;speed:number;damage:number;reward:number};
type SlotView={roomId:string;index:number;x:number;y:number;shape:Phaser.GameObjects.Arc};
const DEPTH_UI=1000;
export class GameplayScene extends Phaser.Scene{
 private session!:GameSession;private sim=new FixedStepSimulation(GAME_DATA.world.simulationStepMs,GAME_DATA.world.maxFrameDeltaMs);private combat=new CombatSystem();private audio=new AudioSystem();private mode!:ModeDefinition;
 private player!:Phaser.GameObjects.Container;private playerAura!:Phaser.GameObjects.Arc;private hunter?:Phaser.GameObjects.Container;private hunterCooldown=0;private cursors!:Phaser.Types.Input.Keyboard.CursorKeys;private wasd?:Record<string,Phaser.Input.Keyboard.Key>;private enemies:EnemyRuntime[]=[];private slots:SlotView[]=[];private doorBars=new Map<string,Phaser.GameObjects.Rectangle>();private selectedBuild='turret';
 private hud!:Phaser.GameObjects.Text;private message!:Phaser.GameObjects.Text;private objective!:Phaser.GameObjects.Text;private startWaveControl?:ReturnType<typeof button>;private buildControls:ReturnType<typeof button>[]=[];private nextSpawnAt=0;private spawnQueue:string[]=[];private waveStarted=false;private allyCooldown=0;private pausedByVisibility=false;private joystick={active:false,pointerId:-1,origin:new Phaser.Math.Vector2(),vector:new Phaser.Math.Vector2()};private joystickBase?:Phaser.GameObjects.Arc;private joystickKnob?:Phaser.GameObjects.Arc;private debugText?:Phaser.GameObjects.Text;private idCounter=0;private tutorialStep=0;
 constructor(){super('Game')}
 init(data:{modeId?:string;tutorial?:boolean}){this.session=new GameSession(data.modeId??'normal',Boolean(data.tutorial));this.mode=GAME_DATA.modes.find(m=>m.id===this.session.state.modeId)??GAME_DATA.modes[1]!}
 create(){const settings=new SaveSystem().load().settings;this.audio.muted=settings.muted;this.audio.unlock();this.session.setPhase('LOADING');this.session.setPhase('MAIN_MENU');this.session.setPhase('MODE_SELECTION');this.session.setPhase('ESCAPE_PHASE');this.cameras.main.setBounds(0,0,GAME_DATA.world.width,GAME_DATA.world.height).setZoom(.72);this.drawWorld();this.createPlayer();this.createHunter();this.createInput();this.createHud();this.bindLifecycle();this.showMessage('Find a glowing door before the Hunter finds you',3200);this.objective.setText('ESCAPE • Reach a room door and press E / INTERACT');this.cameras.main.startFollow(this.player,true,.09,.09);this.cameras.main.fadeIn(350,8,10,25)}
 update(_time:number,delta:number){if(this.session.state.phase==='PAUSED')return;this.sim.advance(delta,dt=>this.fixedUpdate(dt));this.updateHud()}
 private fixedUpdate(dt:number){this.session.state.elapsedMs+=dt*1000;this.movePlayer(dt);if(this.session.state.phase==='ESCAPE_PHASE')this.updateEscape(dt);else if(['DEFENSE_SETUP','WAVE_ACTIVE','WAVE_COMPLETE'].includes(this.session.state.phase)){this.session.tickEconomy(dt*1000);this.updateEnemies(dt);this.updateDefenses(dt);this.updateAllyDefenses(dt);this.updateWave(dt)}this.cleanupDead()}
 private drawWorld(){const g=this.add.graphics();g.fillStyle(0x080b18).fillRect(0,0,1920,1080);g.fillStyle(0x202945).fillRect(0,470,1920,140).fillRect(570,0,780,1080);g.fillStyle(0x2a3554).fillRect(0,510,1920,10).fillRect(900,0,10,1080);for(let x=0;x<1920;x+=60)for(let y=0;y<1080;y+=60){if(this.isFloor(x+30,y+30)){g.lineStyle(1,0x3c4866,.22).strokeRect(x,y,60,60)}}GAME_DATA.rooms.forEach((r,i)=>{g.fillStyle(i%2?0x28213b:0x202a3d).fillRoundedRect(r.x,r.y,r.width,r.height,20);g.lineStyle(8,0x11162c).strokeRoundedRect(r.x,r.y,r.width,r.height,20);g.fillStyle(0x3e3150,.6).fillRect(r.x+22,r.y+22,r.width-44,r.height-44);this.add.text(r.x+25,r.y+20,r.name.toUpperCase(),{fontFamily:'Nunito',fontSize:'16px',fontStyle:'bold',color:'#9ba6d3'});this.drawBed(r);const side=r.doorX===r.x?-1:1;const door=this.add.rectangle(r.doorX+side*5,r.doorY,18,100,0xe1ae66).setStrokeStyle(3,0x4b2d35);door.setData('roomId',r.id);const bar=this.add.rectangle(r.doorX,r.doorY-67,90,8,0x67dd8c).setOrigin(.5);this.doorBars.set(r.id,bar);this.add.rectangle(r.doorX,r.doorY,125,150,0x6d79ff,.04).setStrokeStyle(2,0x8090ff,.6);r.buildSlots.forEach((s,index)=>{const shape=this.add.circle(s[0],s[1],31,0x6170b4,.16).setStrokeStyle(2,0x8392d4,.5);this.slots.push({roomId:r.id,index,x:s[0],y:s[1],shape});shape.setInteractive({useHandCursor:true}).on('pointerup',()=>this.onSlot(index,r.id))})});g.fillStyle(0x11162b).fillCircle(960,540,95);g.lineStyle(6,0x465075,.7).strokeCircle(960,540,95);this.add.text(960,540,'NIGHT\nHALL',{fontFamily:'Nunito',fontSize:'20px',fontStyle:'bold',align:'center',color:'#596589'}).setOrigin(.5)}
 private drawBed(r:RoomDefinition){const g=this.add.graphics();g.fillStyle(0x242036).fillRoundedRect(r.bedX-55,r.bedY-38,110,76,12);g.fillStyle(0x726ea9).fillRoundedRect(r.bedX-48,r.bedY-30,96,60,9);g.fillStyle(0xd9d0bc).fillRoundedRect(r.bedX-40,r.bedY-23,38,22,7);this.add.text(r.bedX,r.bedY+49,'BED',{fontFamily:'Nunito',fontSize:'12px',fontStyle:'bold',color:'#8d98c5'}).setOrigin(.5)}
 private createPlayer(){const shadow=this.add.ellipse(0,17,42,17,0x000000,.35),body=this.add.circle(0,0,20,0xf2cf79).setStrokeStyle(4,0x593f64),face=this.add.circle(6,-3,3,0x29213b);this.playerAura=this.add.circle(0,0,30,0x8fa2ff,.12).setStrokeStyle(2,0x9bb0ff,.4);this.player=this.add.container(960,650,[this.playerAura,shadow,body,face]).setDepth(30);this.player.setData({health:GAME_DATA.player.maxHealth,state:'IDLE',lastDir:1})}
 private createHunter(){const aura=this.add.circle(0,0,37,0xef426f,.13),shadow=this.add.ellipse(0,23,52,17,0,0.4),body=this.add.circle(0,0,26,0x64233c).setStrokeStyle(5,0xe24968),eye1=this.add.circle(-8,-4,3,0xffe8a2),eye2=this.add.circle(8,-4,3,0xffe8a2);this.hunter=this.add.container(960,420,[aura,shadow,body,eye1,eye2]).setDepth(25);this.add.text(960,370,'THE HUNTER',{fontFamily:'Nunito',fontSize:'13px',fontStyle:'bold',color:'#ff6684'}).setOrigin(.5).setData('hunterLabel',true)}
 private createInput(){this.cursors=this.input.keyboard!.createCursorKeys();this.wasd=this.input.keyboard?.addKeys('W,A,S,D,E,SPACE,ESC') as Record<string,Phaser.Input.Keyboard.Key>;this.input.keyboard?.on('keydown-E',()=>this.interact());this.input.keyboard?.on('keydown-SPACE',()=>this.interact());this.input.keyboard?.on('keydown-ESC',()=>this.togglePause());const interact=button(this,1160,635,'INTERACT',()=>this.interact(),170,58);interact.bg.setScrollFactor(0).setDepth(DEPTH_UI);interact.text.setScrollFactor(0).setDepth(DEPTH_UI+1);this.createJoystick();this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>{if(p.x<330&&p.y>390){this.joystick.active=true;this.joystick.pointerId=p.id;this.joystick.origin.set(p.x,p.y);this.joystickBase?.setPosition(p.x,p.y).setVisible(true);this.joystickKnob?.setPosition(p.x,p.y).setVisible(true)}});this.input.on('pointermove',(p:Phaser.Input.Pointer)=>{if(this.joystick.active&&p.id===this.joystick.pointerId){this.joystick.vector.set(p.x-this.joystick.origin.x,p.y-this.joystick.origin.y).limit(55).scale(1/55);this.joystickKnob?.setPosition(this.joystick.origin.x+this.joystick.vector.x*55,this.joystick.origin.y+this.joystick.vector.y*55)}});const release=(p:Phaser.Input.Pointer)=>{if(p.id===this.joystick.pointerId){this.joystick.active=false;this.joystick.vector.set(0);this.joystickBase?.setVisible(false);this.joystickKnob?.setVisible(false)}};this.input.on('pointerup',release);this.input.on('pointerupoutside',release)}
 private createJoystick(){this.joystickBase=this.add.circle(120,600,58,0x283159,.55).setStrokeStyle(2,0x91a1de,.6).setScrollFactor(0).setDepth(DEPTH_UI).setVisible(false);this.joystickKnob=this.add.circle(120,600,24,0x9aabe8,.8).setScrollFactor(0).setDepth(DEPTH_UI+1).setVisible(false);this.add.text(24,674,'Touch + drag to move',{fontFamily:'Nunito',fontSize:'13px',color:'#7886b6'}).setScrollFactor(0).setDepth(DEPTH_UI)}
 private createHud(){const panel=this.add.rectangle(640,36,1260,62,0x090c1c,.9).setStrokeStyle(2,0x354067).setScrollFactor(0).setDepth(DEPTH_UI);this.hud=this.add.text(28,17,'',{fontFamily:'Nunito',fontSize:'18px',fontStyle:'bold',color:'#f5eecb'}).setScrollFactor(0).setDepth(DEPTH_UI+1);this.objective=this.add.text(640,78,'',{fontFamily:'Nunito',fontSize:'16px',fontStyle:'bold',color:'#e8d679',backgroundColor:'#11162bdd',padding:{x:16,y:8}}).setOrigin(.5,0).setScrollFactor(0).setDepth(DEPTH_UI+1);this.message=this.add.text(640,160,'',{fontFamily:'Nunito',fontSize:'25px',fontStyle:'bold',color:'#ffffff',stroke:'#101328',strokeThickness:6,align:'center'}).setOrigin(.5).setScrollFactor(0).setDepth(DEPTH_UI+2).setAlpha(0);const pause=button(this,1228,84,'Ⅱ',()=>this.togglePause(),54,42);pause.bg.setScrollFactor(0).setDepth(DEPTH_UI);pause.text.setScrollFactor(0).setDepth(DEPTH_UI+1);panel.setData('hud',true);if(FEATURES.debugMode)this.debugText=this.add.text(1010,16,'',{fontFamily:'monospace',fontSize:'11px',color:'#7ddba2',align:'right'}).setScrollFactor(0).setDepth(DEPTH_UI+3)}
 private movePlayer(dt:number){if(!['ESCAPE_PHASE','DEFENSE_SETUP','WAVE_ACTIVE','WAVE_COMPLETE'].includes(this.session.state.phase))return;let x=(this.cursors.left.isDown||this.wasd?.A.isDown?-1:0)+(this.cursors.right.isDown||this.wasd?.D.isDown?1:0)+this.joystick.vector.x,y=(this.cursors.up.isDown||this.wasd?.W.isDown?-1:0)+(this.cursors.down.isDown||this.wasd?.S.isDown?1:0)+this.joystick.vector.y;const mag=Math.hypot(x,y);if(mag>0){x/=Math.max(1,mag);y/=Math.max(1,mag);const nx=this.player.x+x*GAME_DATA.player.speed*dt,ny=this.player.y+y*GAME_DATA.player.speed*dt;if(this.isFloor(nx,ny)){this.player.setPosition(nx,ny);this.player.setData('state','MOVING');this.player.setRotation(Math.sin(this.session.state.elapsedMs*.012)*.04);if(x)this.player.setData('lastDir',Math.sign(x))}else this.player.setData('state','IDLE')}else{this.player.setData('state','IDLE');this.player.rotation=0}}
 private isFloor(x:number,y:number){if(x<25||y<25||x>1895||y>1055)return false;if(y>=470&&y<=610)return true;if(x>=570&&x<=1350)return true;return GAME_DATA.rooms.some(r=>x>=r.x+18&&x<=r.x+r.width-18&&y>=r.y+18&&y<=r.y+r.height-18)}
 private interact(){if(this.session.state.phase==='ESCAPE_PHASE'){const room=GAME_DATA.rooms.find(r=>Phaser.Math.Distance.Between(this.player.x,this.player.y,r.doorX,r.doorY)<GAME_DATA.player.interactRange);if(room)this.claim(room);else this.showMessage('Move closer to a glowing room door',900)} }
 private claim(def:RoomDefinition){if(!this.session.claimRoom(def.id))return;this.audio.play('claim');this.hunter?.destroy();this.hunter=undefined;this.children.list.filter(o=>o.getData('hunterLabel')).forEach(o=>o.destroy());this.player.setPosition(def.bedX,def.bedY+90);this.playerAura.setFillStyle(0x65efb2,.16);this.session.setPhase('DEFENSE_SETUP');this.assignAllies();this.showMessage(`${def.name} claimed! The bed is generating gold.`,2200);this.objective.setText('PREPARE • Build defenses, upgrade, then start the wave');this.showBuildUi();this.advanceTutorial(1)}
 private assignAllies(){const options=this.session.state.rooms.filter(r=>r.id!==this.session.state.claimedRoomId).slice(0,2);options.forEach(r=>{r.owner='ALLY';r.lifecycle='DEFENDING';r.doorHealth=220;const def=GAME_DATA.rooms.find(d=>d.id===r.id)!;this.add.text(def.x+def.width/2,def.y+def.height/2,'ALLY SAFEHOUSE',{fontFamily:'Nunito',fontSize:'15px',fontStyle:'bold',color:'#67dca3',backgroundColor:'#101b2acc',padding:{x:9,y:5}}).setOrigin(.5)})}
 private showBuildUi(){const defs=GAME_DATA.buildings;defs.forEach((d,i)=>{const b=button(this,125+i*175,680,`${d.name} • ${d.cost}g`,()=>{this.selectedBuild=d.id;this.highlightSlots()},160,42);b.bg.setScrollFactor(0).setDepth(DEPTH_UI);b.text.setFontSize(13).setScrollFactor(0).setDepth(DEPTH_UI+1);this.buildControls.push(b)});const repair=button(this,850,680,'REPAIR • 20g',()=>{if(this.session.repairDoor()){this.audio.play('build');this.showMessage('Door repaired',700)}else this.showMessage('Cannot repair',700)},145,42);const bed=button(this,1007,680,'BED ↑',()=>{this.actionResult(this.session.upgradeBed(),'Bed upgraded')},125,42);const door=button(this,1147,680,'DOOR ↑',()=>{this.actionResult(this.session.upgradeDoor(),'Door upgraded')},125,42);[repair,bed,door].forEach(b=>{b.bg.setScrollFactor(0).setDepth(DEPTH_UI);b.text.setFontSize(13).setScrollFactor(0).setDepth(DEPTH_UI+1);this.buildControls.push(b)});this.startWaveControl=button(this,1145,115,'START WAVE',()=>this.startWave(),190,46);this.startWaveControl.bg.setScrollFactor(0).setDepth(DEPTH_UI);this.startWaveControl.text.setScrollFactor(0).setDepth(DEPTH_UI+1);this.highlightSlots()}
 private onSlot(index:number,roomId:string){if(roomId!==this.session.state.claimedRoomId||!['DEFENSE_SETUP','WAVE_COMPLETE','WAVE_ACTIVE'].includes(this.session.state.phase))return;const room=this.session.claimedRoom;if(!room)return;if(room.buildings[index]){if(this.session.upgradeBuilding(index)){this.audio.play('upgrade');this.redrawBuilding(index);this.showMessage('Defense upgraded',700)}else this.showMessage('Need more gold or maximum level',850)}else if(this.session.build(index,this.selectedBuild)){this.audio.play('build');this.redrawBuilding(index);this.showMessage('Defense online',700);this.advanceTutorial(2)}else this.showMessage('Not enough gold',750)}
 private redrawBuilding(index:number){const room=this.session.claimedRoom,b=room?.buildings[index],slot=this.slots.find(s=>s.roomId===room?.id&&s.index===index);if(!b||!slot)return;const def=GAME_DATA.buildings.find(d=>d.id===b.definitionId)!;slot.shape.setFillStyle(def.color,.86).setStrokeStyle(3,0xffffff,.7).setRadius(25+b.level*2);slot.shape.setData('building',b.definitionId);this.add.text(slot.x,slot.y,String(b.level),{fontFamily:'Nunito',fontSize:'15px',fontStyle:'bold',color:'#101329'}).setOrigin(.5).setDepth(slot.shape.depth+1)}
 private highlightSlots(){this.slots.forEach(s=>{const active=s.roomId===this.session.state.claimedRoomId;s.shape.setStrokeStyle(active?3:2,active?0xffe477:0x8392d4,active ? .9 : .25)})}
 private startWave(){if(!['DEFENSE_SETUP','WAVE_COMPLETE'].includes(this.session.state.phase)||this.waveStarted)return;if(this.session.state.wave>=GAME_DATA.waves.length)return;this.session.state.wave++;this.session.setPhase('WAVE_ACTIVE');this.waveStarted=true;const wave=GAME_DATA.waves[this.session.state.wave-1]!;this.spawnQueue=wave.groups.flatMap(g=>Array.from({length:g.count},()=>g.enemyId));this.nextSpawnAt=0;this.startWaveControl?.setEnabled(false);this.audio.play('wave');this.session.events.emit('WAVE_STARTED',{wave:wave.id});this.objective.setText(`WAVE ${wave.id} • Protect every safehouse`);this.showMessage(wave.boss?'BOSS WAVE — THE NIGHT KEEPER APPROACHES!':`Wave ${wave.id} begins`,1600)}
 private updateWave(dt:number){if(!this.waveStarted||this.session.state.phase!=='WAVE_ACTIVE')return;this.nextSpawnAt-=dt*1000;if(this.spawnQueue.length&&this.nextSpawnAt<=0){const id=this.spawnQueue.shift()!;this.spawnEnemy(id);const wave=GAME_DATA.waves[this.session.state.wave-1]!,group=wave.groups.find(g=>g.enemyId===id)!;this.nextSpawnAt=group.spawnIntervalMs}if(!this.spawnQueue.length&&!this.enemies.some(e=>e.alive)){this.waveStarted=false;this.session.events.emit('WAVE_COMPLETED',{wave:this.session.state.wave});if(this.session.state.wave>=GAME_DATA.waves.length){this.win()}else{this.session.setPhase('WAVE_COMPLETE');this.session.setPhase('DEFENSE_SETUP');this.startWaveControl?.setEnabled(true);this.objective.setText('BREATHER • Repair, upgrade, and start the next wave');this.showMessage(`Wave ${this.session.state.wave} cleared`,1600);this.economyWaveReward()}}}
 private economyWaveReward(){this.session.economy.earn(35+this.session.state.wave*15)}
 private spawnEnemy(type:string){const def=GAME_DATA.enemies.find(e=>e.id===type);if(!def)return;const angle=(this.idCounter*2.399)%6.28,radius=80+(this.idCounter%3)*25,x=960+Math.cos(angle)*radius,y=540+Math.sin(angle)*radius;const shape=this.add.circle(0,0,type==='boss'?34:type==='brute'?25:18,def.color).setStrokeStyle(3,0x160d24),eyes=this.add.circle(5,-3,3,0xffecaa),barBg=this.add.rectangle(0,-34,type==='boss'?80:48,6,0x291528),bar=this.add.rectangle(-(type==='boss'?40:24),-34,type==='boss'?80:48,6,0x77df8f).setOrigin(0,.5),body=this.add.container(x,y,[shape,eyes,barBg,bar]).setDepth(20);const target=this.chooseTargetRoom(x,y);const enemy:EnemyRuntime={id:`enemy-${++this.idCounter}`,type,def,body,shape,hpBar:bar,state:'SPAWNING',health:def.maxHealth*this.mode.enemyHealth,maxHealth:def.maxHealth*this.mode.enemyHealth,alive:true,cooldown:0,targetRoomId:target?.id??this.session.state.claimedRoomId,speed:def.speed*this.mode.enemySpeed,damage:def.damage*this.mode.enemyDamage,reward:def.reward*this.mode.reward};this.enemies.push(enemy);enemy.state='SEARCHING';if(type==='boss')this.session.events.emit('BOSS_SPAWNED',{id:enemy.id});this.session.events.emit('ENEMY_SPAWNED',{id:enemy.id,type});this.flash(x,y,def.color)}
 private chooseTargetRoom(x:number,y:number){const available=this.session.state.rooms.filter(r=>r.owner&&r.lifecycle!=='DEFEATED');return available.sort((a,b)=>{const da=GAME_DATA.rooms.find(d=>d.id===a.id)!,db=GAME_DATA.rooms.find(d=>d.id===b.id)!;return Phaser.Math.Distance.Squared(x,y,da.doorX,da.doorY)-Phaser.Math.Distance.Squared(x,y,db.doorX,db.doorY)})[0]}
 private updateEnemies(dt:number){for(const e of this.enemies){if(!e.alive)continue;e.cooldown=Math.max(0,e.cooldown-dt*1000);let room=e.targetRoomId?this.session.state.rooms.find(r=>r.id===e.targetRoomId):undefined;if(!room||room.lifecycle==='DEFEATED') {room=this.chooseTargetRoom(e.body.x,e.body.y);e.targetRoomId=room?.id??null}if(!room)continue;const rd=GAME_DATA.rooms.find(r=>r.id===room!.id)!;const doorAlive=room.doorHealth>0;const tx=doorAlive?rd.doorX:(room.owner==='PLAYER'?this.player.x:rd.bedX),ty=doorAlive?rd.doorY:(room.owner==='PLAYER'?this.player.y:rd.bedY);const dist=Phaser.Math.Distance.Between(e.body.x,e.body.y,tx,ty);if(dist>(doorAlive?e.def.attackRange:32)){e.state='MOVING';const dx=(tx-e.body.x)/Math.max(1,dist),dy=(ty-e.body.y)/Math.max(1,dist);e.body.x+=dx*e.speed*dt;e.body.y+=dy*e.speed*dt;e.body.rotation=Math.sin(this.session.state.elapsedMs*.01+this.idCounter)*.03}else if(e.cooldown<=0){e.state='ATTACKING';e.cooldown=e.def.attackCooldownMs;if(doorAlive)this.enemyHitDoor(e,room);else if(room.owner==='PLAYER')this.enemyHitPlayer(e);else this.defeatAlly(room)}e.hpBar.width=(e.type==='boss'?80:48)*(e.health/e.maxHealth)}this.updateDoorBars()}
 private enemyHitDoor(e:EnemyRuntime,room:RoomState){room.doorHealth=Math.max(0,room.doorHealth-e.damage);this.audio.play('hit');this.shake(55,.003);this.flash(e.body.x,e.body.y,0xff6b7e);this.session.events.emit('DOOR_DAMAGED',{roomId:room.id,amount:e.damage,health:room.doorHealth});if(room.doorHealth===0){this.audio.play('break');room.lifecycle='BREACHED';this.session.events.emit('DOOR_BROKEN',{roomId:room.id});if(room.owner==='PLAYER')this.showMessage('THE DOOR IS BROKEN — enemies are inside!',1800);else this.defeatAlly(room)}}
 private enemyHitPlayer(e:EnemyRuntime){this.session.state.playerHealth=Math.max(0,this.session.state.playerHealth-e.damage);this.playerAura.setFillStyle(0xff3f68,.4);this.time.delayedCall(120,()=>this.playerAura?.setFillStyle(0x65efb2,.16));this.shake(110,.008);if(!this.session.state.playerHealth)this.lose('The darkness reached your bed')}
 private defeatAlly(room:RoomState){if(room.lifecycle==='DEFEATED')return;room.lifecycle='DEFEATED';room.doorHealth=0;this.showMessage('An ally safehouse has fallen — enemies grow stronger',1500);this.enemies.forEach(e=>{e.damage*=1.12;e.speed*=1.04;if(e.targetRoomId===room.id)e.targetRoomId=null})}
 private updateDefenses(dt:number){const room=this.session.claimedRoom;if(!room)return;const radar=room.buildings.some(b=>b?.definitionId==='radar');room.buildings.forEach((b,index)=>{if(!b?.active)return;b.cooldownRemaining=Math.max(0,b.cooldownRemaining-dt*1000);const def=GAME_DATA.buildings.find(d=>d.id===b.definitionId)!;if(def.kind==='RADAR')return;const slot=GAME_DATA.rooms.find(r=>r.id===room.id)!.buildSlots[index]!;const range=def.range*(radar?1.3:1);const targets=this.enemies.filter(e=>e.alive&&Phaser.Math.Distance.Between(slot[0],slot[1],e.body.x,e.body.y)<=range).sort((a,c)=>Phaser.Math.Distance.Squared(slot[0],slot[1],a.body.x,a.body.y)-Phaser.Math.Distance.Squared(slot[0],slot[1],c.body.x,c.body.y));if(!targets.length||b.cooldownRemaining>0)return;const damage=def.damage*(1+(b.level-1)*.65);if(def.kind==='TESLA'){targets.slice(0,b.level+1).forEach(e=>{this.arc(slot[0],slot[1],e.body.x,e.body.y);this.damageEnemy(e,damage)});b.cooldownRemaining=def.cooldownMs}else if(def.kind==='MINE'){const close=targets.find(e=>Phaser.Math.Distance.Between(slot[0],slot[1],e.body.x,e.body.y)<def.range);if(close){this.flash(slot[0],slot[1],def.color,58);targets.forEach(e=>this.damageEnemy(e,damage));b.cooldownRemaining=def.cooldownMs}}else{this.projectile(slot[0],slot[1],targets[0]!,damage,def.color);b.cooldownRemaining=def.cooldownMs/(1+(b.level-1)*.16)}})}
 private updateAllyDefenses(dt:number){this.allyCooldown-=dt*1000;if(this.allyCooldown>0)return;this.allyCooldown=950;for(const room of this.session.state.rooms.filter(r=>r.owner==='ALLY'&&r.lifecycle!=='DEFEATED')){const rd=GAME_DATA.rooms.find(d=>d.id===room.id)!;const target=this.enemies.filter(e=>e.alive).sort((a,b)=>Phaser.Math.Distance.Squared(rd.bedX,rd.bedY,a.body.x,a.body.y)-Phaser.Math.Distance.Squared(rd.bedX,rd.bedY,b.body.x,b.body.y))[0];if(target&&Phaser.Math.Distance.Between(rd.bedX,rd.bedY,target.body.x,target.body.y)<390)this.projectile(rd.bedX,rd.bedY,target,11,0x68dca3)}}
 private projectile(x:number,y:number,target:EnemyRuntime,damage:number,color:number){if(!target.alive)return;this.audio.play('shot');const p=this.add.circle(x,y,5,color).setDepth(40);this.tweens.add({targets:p,x:target.body.x,y:target.body.y,duration:130,onComplete:()=>{p.destroy();if(target.alive){this.damageEnemy(target,damage);this.flash(target.body.x,target.body.y,color,16)}}})}
 private damageEnemy(e:EnemyRuntime,amount:number){const result=this.combat.damage({sourceId:'defense',target:e,amount});if(result.killed){e.state='DYING';this.session.economy.earn(Math.floor(e.reward));this.session.events.emit('ENEMY_DIED',{id:e.id,type:e.type});this.tweens.add({targets:e.body,alpha:0,scale:.3,duration:240,onComplete:()=>e.body.destroy()})}else{e.state='HIT';e.shape.setAlpha(.45);this.time.delayedCall(65,()=>{if(e.shape.active)e.shape.setAlpha(1)})}}
 private cleanupDead(){this.enemies=this.enemies.filter(e=>e.alive||e.body.active)}
 private updateEscape(dt:number){if(!this.hunter)return;this.hunterCooldown=Math.max(0,this.hunterCooldown-dt*1000);const d=Phaser.Math.Distance.Between(this.hunter.x,this.hunter.y,this.player.x,this.player.y),dx=(this.player.x-this.hunter.x)/Math.max(1,d),dy=(this.player.y-this.hunter.y)/Math.max(1,d);const nx=this.hunter.x+dx*GAME_DATA.hunter.speed*dt,ny=this.hunter.y+dy*GAME_DATA.hunter.speed*dt;if(this.isFloor(nx,ny))this.hunter.setPosition(nx,ny);else{if(this.isFloor(nx,this.hunter.y))this.hunter.x=nx;if(this.isFloor(this.hunter.x,ny))this.hunter.y=ny}if(d<GAME_DATA.hunter.attackRange&&this.hunterCooldown<=0){this.hunterCooldown=GAME_DATA.hunter.attackCooldownMs;this.session.state.playerHealth=Math.max(0,this.session.state.playerHealth-GAME_DATA.hunter.escapeDamage);this.audio.play('hit');this.shake(130,.012);this.showMessage(`The Hunter struck! ${this.session.state.playerHealth} health`,700);if(!this.session.state.playerHealth)this.lose('The Hunter caught you before you found safety')}}
 private updateDoorBars(){this.session.state.rooms.forEach(r=>{const bar=this.doorBars.get(r.id),max=r.owner==='ALLY'?220:GAME_DATA.doorLevels[r.doorLevel-1]!.maxHealth;if(bar){bar.width=90*Math.max(0,r.doorHealth/max);bar.setFillStyle(r.doorHealth/max<.3?0xf24f68:0x67dd8c);bar.setVisible(Boolean(r.owner))}})}
 private updateHud(){const room=this.session.claimedRoom,door=room?`${Math.ceil(room.doorHealth)}/${GAME_DATA.doorLevels[room.doorLevel-1]!.maxHealth}`:'—';this.hud.setText(`◈ ${this.session.state.gold} GOLD     ♥ ${Math.ceil(this.session.state.playerHealth)}     WAVE ${this.session.state.wave}/${GAME_DATA.waves.length}     DOOR ${door}     ${this.mode.name.toUpperCase()}`);if(this.debugText)this.debugText.setText(`FPS ${Math.round(this.game.loop.actualFps)} | ${this.session.state.phase}\nEnemies ${this.enemies.filter(e=>e.alive).length} | Player ${Math.round(this.player.x)},${Math.round(this.player.y)}\nSeed ${this.session.state.seed} | Save v1`)}
 private togglePause(){if(this.session.state.phase==='PAUSED'){const resume=this.session.state.previousPhase??'DEFENSE_SETUP';this.session.setPhase(resume as never);this.message.setAlpha(0)}else if(['ESCAPE_PHASE','DEFENSE_SETUP','WAVE_ACTIVE','WAVE_COMPLETE'].includes(this.session.state.phase)){this.session.setPhase('PAUSED');this.showMessage('PAUSED\nPress Escape to resume',999999)}}
 private bindLifecycle(){const vis=()=>{if(document.hidden&&this.session.state.phase!=='PAUSED'){this.pausedByVisibility=true;this.togglePause()}else if(!document.hidden&&this.pausedByVisibility){this.pausedByVisibility=false}};document.addEventListener('visibilitychange',vis);this.events.once('shutdown',()=>{document.removeEventListener('visibilitychange',vis);this.audio.close();this.session.events.clear()});const pagehide=()=>this.saveProgressSnapshot();window.addEventListener('pagehide',pagehide);this.events.once('shutdown',()=>window.removeEventListener('pagehide',pagehide))}
 private saveProgressSnapshot(){const saves=new SaveSystem(),s=saves.load();s.lastMode=this.mode.id;saves.save(s)}
 private persist(win:boolean){const saves=new SaveSystem(),s=saves.load();if(win){s.progression.wins++;if(s.progression.wins>=1&&!s.progression.unlockedModes.includes('hard'))s.progression.unlockedModes.push('hard')}else s.progression.losses++;s.lastMode=this.mode.id;saves.save(s)}
 private win(){this.session.setPhase('VICTORY');this.persist(true);this.audio.play('victory');this.endOverlay(true,'DAWN BREAKS','The Night Keeper is gone. Every surviving room sees morning.')}
 private lose(reason:string){if(['DEFEAT','VICTORY'].includes(this.session.state.phase))return;this.session.setPhase('DEFEAT',true);this.persist(false);this.audio.play('defeat');this.endOverlay(false,'THE NIGHT WON',reason)}
 private endOverlay(won:boolean,heading:string,copy:string){this.startWaveControl?.setEnabled(false);this.add.rectangle(640,360,1280,720,0x050713,.86).setScrollFactor(0).setDepth(2000);this.add.text(640,225,heading,{fontFamily:'Nunito',fontSize:'58px',fontStyle:'900',color:won?'#ffe88b':'#ff6684',stroke:'#151226',strokeThickness:9}).setOrigin(.5).setScrollFactor(0).setDepth(2001);this.add.text(640,300,copy,{fontFamily:'Nunito',fontSize:'20px',color:'#c2cae9',align:'center',wordWrap:{width:620}}).setOrigin(.5).setScrollFactor(0).setDepth(2001);const retry=button(this,640,405,'PLAY AGAIN',()=>this.scene.restart({modeId:this.mode.id,tutorial:false}),240);const menu=button(this,640,480,'MAIN MENU',()=>this.scene.start('Menu'),240);[retry,menu].forEach(b=>{b.bg.setScrollFactor(0).setDepth(2002);b.text.setScrollFactor(0).setDepth(2003)})}
 private actionResult(ok:boolean,message:string){if(ok){this.audio.play('upgrade');this.showMessage(message,700);this.advanceTutorial(3)}else this.showMessage('Need more gold or maximum level',850)}
 private showMessage(text:string,duration:number){this.message.setText(text).setAlpha(1);this.tweens.killTweensOf(this.message);this.tweens.add({targets:this.message,alpha:0,delay:duration,duration:260})}
 private advanceTutorial(step:number){if(!this.session.state.tutorial||step<=this.tutorialStep)return;this.tutorialStep=step;const hints=['','Good. Your bed earns gold automatically. Build on a glowing slot.','Now upgrade by tapping the built defense again.','Ready. Start the wave when your defenses are set.'];this.showMessage(hints[step]??'',2200)}
 private flash(x:number,y:number,color:number,radius=32){const c=this.add.circle(x,y,6,color,.8).setDepth(35);this.tweens.add({targets:c,scale:radius/6,alpha:0,duration:220,onComplete:()=>c.destroy()})}
 private arc(x1:number,y1:number,x2:number,y2:number){const g=this.add.graphics().setDepth(39);g.lineStyle(4,0x69dfff,.9).lineBetween(x1,y1,x2,y2);this.tweens.add({targets:g,alpha:0,duration:100,onComplete:()=>g.destroy()})}
 private shake(duration:number,intensity:number){if(!new SaveSystem().load().settings.reducedMotion)this.cameras.main.shake(duration,intensity)}
}
