import dataJson from '../data/production/game.json';
import type { GameData,SessionState,RoomState,BuildingState } from '../types/game';
import { GameEventBus } from '../systems/GameEventBus';import { EconomySystem } from '../systems/EconomySystem';import { GameStateMachine } from '../systems/GameStateMachine';
export const GAME_DATA=dataJson as GameData;
export class GameSession{
 readonly events=new GameEventBus();readonly machine=new GameStateMachine('BOOT');readonly economy:EconomySystem;readonly state:SessionState;private goldRemainder=0;
 constructor(modeId='normal',tutorial=false,seed=Date.now()){this.state={phase:'BOOT',previousPhase:null,modeId,gold:GAME_DATA.economy.startingGold,wave:0,playerHealth:GAME_DATA.player.maxHealth,claimedRoomId:null,rooms:GAME_DATA.rooms.map<RoomState>(r=>({id:r.id,lifecycle:'EMPTY',owner:null,doorLevel:1,doorHealth:GAME_DATA.doorLevels[0]!.maxHealth,bedLevel:1,buildings:r.buildSlots.map(()=>null)})),elapsedMs:0,seed,tutorial};this.economy=new EconomySystem(()=>this.state.gold,v=>this.state.gold=v,this.events)}
 setPhase(next:SessionState['phase'],force=false){const from=this.machine.state;if(!(force? (this.machine.force(next),true):this.machine.transition(next)))return false;this.state.previousPhase=from;this.state.phase=next;this.events.emit('PHASE_CHANGED',{from,to:next});return true}
 claimRoom(id:string){const room=this.state.rooms.find(r=>r.id===id);if(!room||room.lifecycle!=='EMPTY'||this.state.claimedRoomId)return false;room.lifecycle='LOCKED';room.owner='PLAYER';this.state.claimedRoomId=id;this.setPhase('ROOM_CLAIMED');this.events.emit('ROOM_CLAIMED',{roomId:id});return true}
 tickEconomy(deltaMs:number){const room=this.claimedRoom;if(!room||!['DEFENSE_SETUP','WAVE_ACTIVE','WAVE_COMPLETE'].includes(this.state.phase))return;const level=GAME_DATA.bedLevels[room.bedLevel-1];if(!level)return;this.goldRemainder+=level.goldPerSecond*deltaMs/1000;const whole=Math.floor(this.goldRemainder);if(whole){this.goldRemainder-=whole;this.economy.earn(whole)}}
 build(slot:number,id:string){const room=this.claimedRoom,def=GAME_DATA.buildings.find(b=>b.id===id);if(!room||!def||!Number.isInteger(slot)||slot<0||slot>=room.buildings.length||room.buildings[slot]!==null)return false;return this.economy.purchase(`build-${slot}-${id}`,def.cost,()=>{room.buildings[slot]={definitionId:id,level:1,cooldownRemaining:0,active:true};this.events.emit('ITEM_BUILT',{id,slot});return true})}
 upgradeBuilding(slot:number){const room=this.claimedRoom,b=room?.buildings[slot];if(!room||!b||b.level>=3)return false;const def=GAME_DATA.buildings.find(x=>x.id===b.definitionId);if(!def)return false;const cost=Math.floor(def.upgradeCost*Math.pow(1.55,b.level-1));return this.economy.purchase(`upgrade-${slot}-${b.level}`,cost,()=>{b.level++;this.events.emit('ITEM_UPGRADED',{id:b.definitionId,level:b.level});return true})}
 upgradeBed(){const room=this.claimedRoom;if(!room)return false;const level=GAME_DATA.bedLevels[room.bedLevel-1];if(!level?.upgradeCost)return false;return this.economy.purchase(`bed-${room.bedLevel}`,level.upgradeCost,()=>{room.bedLevel++;return true})}
 upgradeDoor(){const room=this.claimedRoom;if(!room)return false;const level=GAME_DATA.doorLevels[room.doorLevel-1];if(!level?.upgradeCost)return false;return this.economy.purchase(`door-${room.doorLevel}`,level.upgradeCost,()=>{room.doorLevel++;room.doorHealth=GAME_DATA.doorLevels[room.doorLevel-1]!.maxHealth;return true})}
 repairDoor(){const room=this.claimedRoom;if(!room)return false;const max=GAME_DATA.doorLevels[room.doorLevel-1]!.maxHealth;if(room.doorHealth>=max)return false;return this.economy.purchase(`repair-${Math.floor(this.state.elapsedMs/250)}`,GAME_DATA.economy.repairCost,()=>{room.doorHealth=Math.min(max,room.doorHealth+GAME_DATA.economy.repairAmount);return true})}
 damageDoor(amount:number){const room=this.claimedRoom;if(!room||room.doorHealth<=0)return false;room.doorHealth=Math.max(0,room.doorHealth-amount);this.events.emit('DOOR_DAMAGED',{roomId:room.id,amount,health:room.doorHealth});if(!room.doorHealth){room.lifecycle='BREACHED';this.events.emit('DOOR_BROKEN',{roomId:room.id})}return true}
 get claimedRoom(){return this.state.rooms.find(r=>r.id===this.state.claimedRoomId)}
 resetCooldowns(){this.claimedRoom?.buildings.forEach((b:BuildingState|null)=>{if(b)b.cooldownRemaining=0})}
}
